### ISSUE TITLE
Help with motionMode

### ISSUE THREAD

**Issue by Scott216** [bilbolodz/MMA8451#1]
I got the datamode example sketch to work on a Leonardo and a MMA8452Q, but I can't get the motionmode or shakemode working.  I don't have anything connected to Arduino pins 2 or 3.  Do these two sketches need one or both of of these interrupt pins to be wired in order for it to work?  If so, what do I wire them too?

Also, I'm confused by the comment:
enable MMA8453Q INT pin 2 (false= pin 1)
can you explain this a bit.  I don't know what you mean by false= pin 1

**Comment by bilbolodz** [comment]
Actually I've not used motionmode or shakemode in my application. I'm not an author of these library I only modified it to work with MMA8451 so if you have "deeper" questions I suggest contact author. In my app I'm using datamode with interrupt.

**Comment by Scott216** [comment]
I didn't realize you weren't the author.  I'll send him a message.  I think I figured out my problem.  I'm using a Leonardo which uses I2C on D2 and D3, which are the same pins this library uses for interrupts.
